update blog link
matplotlib/mpl-brochure-site pull request #62
Opened 2022-09-20 03:57 UTC by story645

Changed it to the scientific python blog since we no longer maintain it; alternatively it could be removed?

2022-09-20 04:34 UTC, QuLogic commented
Should we add redirects to the server for the existing blog?

2023-09-14 17:57 UTC, ksunden commented
Build failure appears to be the same as https://github.com/matplotlib/matplotlib/pull/26493

2023-09-14 20:25 UTC, QuLogic commented
Should be fixed in #84.

2023-09-15 07:28 UTC, timhoffm approved these changes

2023-09-15 07:29 UTC, QuLogic requested changes
This includes a second rebased copy of my commit in #84.

2023-09-15 20:49 UTC, QuLogic approved these changes

2023-09-15 20:49 UTC, merged